<?php
if (!defined('ABSPATH')) exit;

/**
 * Panam Runtime CSS Generator
 * Writes: /assets/css/runtime.css
 *
 * Requirements:
 * - inc/design-tokens.php included (panam_scale, panam_on_color, etc.)
 * - assets.php enqueues panam-runtime after panam-main
 */

function panam_runtime_css_path(): string {
  return trailingslashit(get_template_directory()) . 'assets/css/runtime.css';
}

function panam_runtime_css_url(): string {
  return trailingslashit(get_template_directory_uri()) . 'assets/css/runtime.css';
}

function panam_safe_hex(string $hex, string $fallback): string {
  $hex = sanitize_hex_color($hex);
  return $hex ? $hex : $fallback;
}

function panam_build_runtime_css(): string {
  // Read settings
  $primary   = panam_safe_hex((string) panam_get_theme_setting('primary_color', '#111827'), '#111827');
  $secondary = panam_safe_hex((string) panam_get_theme_setting('secondary_color', '#6b7280'), '#6b7280');
  $accent    = panam_safe_hex((string) panam_get_theme_setting('accent_color', '#22c55e'), '#22c55e');

  $mode = (string) panam_get_theme_setting('color_mode', 'auto');
  if (!in_array($mode, ['auto', 'light', 'dark'], true)) $mode = 'auto';

  // Derived palettes
  $p = function_exists('panam_scale') ? panam_scale($primary) : [];
  $s = function_exists('panam_scale') ? panam_scale($secondary) : [];
  $a = function_exists('panam_scale') ? panam_scale($accent) : [];

  // Derived on-colors
  $on_primary   = function_exists('panam_on_color') ? panam_on_color($primary) : '#ffffff';
  $on_secondary = function_exists('panam_on_color') ? panam_on_color($secondary) : '#ffffff';
  $on_accent    = function_exists('panam_on_color') ? panam_on_color($accent) : '#111827';

  // Hover/active fallbacks if scale isn't available for some reason
  $primary_hover   = $p['600'] ?? $primary;
  $primary_active  = $p['700'] ?? $primary;

  $secondary_hover  = $s['600'] ?? $secondary;
  $secondary_active = $s['700'] ?? $secondary;

  $accent_hover  = $a['600'] ?? $accent;
  $accent_active = $a['700'] ?? $accent;

  $css  = "/* Auto-generated by Panam. Do not edit this file directly. */\n";
  $css .= "/* Generated: " . gmdate('c') . " */\n\n";

  // Base variables always present
  $css .= ":root{\n";

  // Let runtime control color-scheme for forced modes
  if ($mode === 'light') $css .= "  color-scheme: light;\n";
  if ($mode === 'dark')  $css .= "  color-scheme: dark;\n";

  // Brand colors
  $css .= "  --panam-primary: {$primary};\n";
  $css .= "  --panam-primary-hover: {$primary_hover};\n";
  $css .= "  --panam-primary-active: {$primary_active};\n";
  $css .= "  --panam-on-primary: {$on_primary};\n";

  $css .= "  --panam-secondary: {$secondary};\n";
  $css .= "  --panam-secondary-hover: {$secondary_hover};\n";
  $css .= "  --panam-secondary-active: {$secondary_active};\n";
  $css .= "  --panam-on-secondary: {$on_secondary};\n";

  $css .= "  --panam-accent: {$accent};\n";
  $css .= "  --panam-accent-hover: {$accent_hover};\n";
  $css .= "  --panam-accent-active: {$accent_active};\n";
  $css .= "  --panam-on-accent: {$on_accent};\n";

  // Optional: full scales (useful for UI)
  if (!empty($p)) foreach ($p as $k => $v) $css .= "  --panam-primary-{$k}: {$v};\n";
  if (!empty($s)) foreach ($s as $k => $v) $css .= "  --panam-secondary-{$k}: {$v};\n";
  if (!empty($a)) foreach ($a as $k => $v) $css .= "  --panam-accent-{$k}: {$v};\n";

  $css .= "}\n\n";

  /**
   * Surface + text tokens
   * - Auto mode: match system preference via media query
   * - Forced modes: set directly on :root
   *
   * Your main.css should use:
   * --panam-bg, --panam-fg, --panam-muted, --panam-border, --panam-surface
   */
  $light_tokens  = "  --panam-bg: #ffffff;\n";
  $light_tokens .= "  --panam-fg: #111827;\n";
  $light_tokens .= "  --panam-muted: #6b7280;\n";
  $light_tokens .= "  --panam-border: #e5e7eb;\n";
  $light_tokens .= "  --panam-surface: #f9fafb;\n";

  $dark_tokens  = "  --panam-bg: #0b0f19;\n";
  $dark_tokens .= "  --panam-fg: #e5e7eb;\n";
  $dark_tokens .= "  --panam-muted: #9ca3af;\n";
  $dark_tokens .= "  --panam-border: rgba(255,255,255,.12);\n";
  $dark_tokens .= "  --panam-surface: rgba(255,255,255,.04);\n";

  if ($mode === 'light') {
    $css .= ":root{\n{$light_tokens}}\n";
  } elseif ($mode === 'dark') {
    $css .= ":root{\n{$dark_tokens}}\n";
  } else {
    // auto
    $css .= ":root{\n{$light_tokens}}\n";
    $css .= "@media (prefers-color-scheme: dark){\n";
    $css .= "  :root{\n{$dark_tokens}  }\n";
    $css .= "}\n";
  }

  return $css;
}

function panam_write_runtime_css(): void {
  $path = panam_runtime_css_path();
  $dir  = dirname($path);

  if (!is_dir($dir)) {
    @wp_mkdir_p($dir);
  }

  $css = panam_build_runtime_css();

  // Try to write file
  @file_put_contents($path, $css);
}

/**
 * Generate when settings are saved
 * update_option_{option_name} fires after update_option()
 */
add_action('update_option_' . PANAM_THEME_OPTIONS_KEY, function ($old, $new) {
  // Only run in admin, and only when actually changed
  if (!is_admin()) return;
  panam_write_runtime_css();
}, 10, 2);

/**
 * Generate on theme switch (first install)
 */
add_action('after_switch_theme', function () {
  panam_write_runtime_css();
});

/**
 * Safety net: if runtime.css is missing, attempt to generate on frontend init.
 * (Helps when files get deleted, or permissions change.)
 */
add_action('init', function () {
  $path = panam_runtime_css_path();
  if (!file_exists($path)) {
    panam_write_runtime_css();
  }
});