<?php
if (!defined('ABSPATH')) exit;

function panam_write_runtime_css(): void {
  $primary   = sanitize_hex_color(panam_get_theme_setting('primary_color', '#111827')) ?: '#111827';
  $secondary = sanitize_hex_color(panam_get_theme_setting('secondary_color', '#6b7280')) ?: '#6b7280';
  $accent    = sanitize_hex_color(panam_get_theme_setting('accent_color', '#22c55e')) ?: '#22c55e';

  $mode = panam_get_theme_setting('color_mode', 'auto');
  $mode = in_array($mode, ['auto','light','dark'], true) ? $mode : 'auto';

  $p = panam_scale($primary);
  $s = panam_scale($secondary);
  $a = panam_scale($accent);

  $css  = "/* Auto-generated by Panam. Do not edit. */\n";
  $css .= ":root{\n";
  $css .= "  --panam-primary: {$primary};\n";
  $css .= "  --panam-primary-hover: {$p['600']};\n";
  $css .= "  --panam-primary-active: {$p['700']};\n";
  $css .= "  --panam-on-primary: " . panam_on_color($primary) . ";\n";

  $css .= "  --panam-secondary: {$secondary};\n";
  $css .= "  --panam-secondary-hover: {$s['600']};\n";
  $css .= "  --panam-secondary-active: {$s['700']};\n";
  $css .= "  --panam-on-secondary: " . panam_on_color($secondary) . ";\n";

  $css .= "  --panam-accent: {$accent};\n";
  $css .= "  --panam-accent-hover: {$a['600']};\n";
  $css .= "  --panam-accent-active: {$a['700']};\n";
  $css .= "  --panam-on-accent: " . panam_on_color($accent) . ";\n";

  // Scales
  foreach ($p as $k => $v) { $css .= "  --panam-primary-{$k}: {$v};\n"; }
  foreach ($s as $k => $v) { $css .= "  --panam-secondary-{$k}: {$v};\n"; }
  foreach ($a as $k => $v) { $css .= "  --panam-accent-{$k}: {$v};\n"; }

  // Mode hint
  if ($mode === 'light') $css .= "  color-scheme: light;\n";
  if ($mode === 'dark')  $css .= "  color-scheme: dark;\n";

  $css .= "}\n\n";

  // Dark mode variables (system) if auto
  if ($mode === 'auto') {
    $css .= "@media (prefers-color-scheme: dark){\n";
    $css .= "  :root{\n";
    // In dark mode, we keep brand colors but shift surfaces/text (you can tune these later)
    $css .= "    --panam-surface: #0b0f19;\n";
    $css .= "    --panam-text: #e5e7eb;\n";
    $css .= "    --panam-border: rgba(255,255,255,.12);\n";
    $css .= "  }\n";
    $css .= "}\n";
  }

  $path = get_template_directory() . '/assets/css/runtime.css';
  // Try direct write first
  @file_put_contents($path, $css);
}

add_action('update_option_' . PANAM_THEME_OPTIONS_KEY, function () {
  panam_write_runtime_css();
}, 10, 0);

// Also generate on theme switch / first run
add_action('after_switch_theme', function () {
  panam_write_runtime_css();
});